### ISSUE TITLE
Program class does not return the whole program

### ISSUE THREAD

**Issue by Sitiritis** [polystat/polystat#16]
Restating the request from #13.

> There is a problem with the `Program` class. When I pass it `"\\Phi"` as a locator I expect it to return me all the objects from the sources to be analyzed, but instead I get an exception, so `OdinAnalysis::errors` now throws an exception at the stage of `xmir.apply("\\Phi")`.

**Comment by yegor256** [comment]
@Sitiritis I'm not sure this is a legal operation... why would any analyzer need to see the _entire_ object scope in one XML? The `Program` class is there specifically to avoid such requests. You are supposed to fetch object by object, instead of fetching everything and then re-implementing the `Program` on your side. Make sense?

**Comment by yegor256** [comment]
@Sitiritis I believe it's time to close this. We should analyze objects, not programs.
